#!/bin/sh
PGDATA="/var/db/pgsql"
PGBACKUP_DIR="/var/db/pgsql_backup"
PGARCHIVE_DIR=$PGBACKUP_DIR/archive
PGARCHIVE_TRIGGER_FILE=$PGBACKUP_DIR/archiving_active

ARCHIVE_USER=pgsql
ARCHIVE_SERVER=xxx.xxx.xxx.xxx
ARCHIVE_SERVER_SSH_PORT=22

# 0: local 
# 1: remote via ssh
# 2: remote via rsync
PGARCHIVE_MODE="1" 
