#!/bin/sh
PGDIR="pgsql"
PGPARENT="/var/db"
PGDATA=$PGPARENT/$PGDIR
PGBACKUP_DIR=$PGPARENT/pgsql_backup
PGARCHIVE_DIR=$PGBACKUP_DIR/archive
PGARCHIVE_TRIGGER_FILE=$PGBACKUP_DIR/archiving_active
PGBACKUP_FILE=`date +"%Y%m%d%H%M%S"`

PGTRIGGER_FILE=$PGBACKUP_DIR/postgresql.trigger.standby

# 0: archive locally
# 1: archive remote via ssh
# 2: archive locally + archive remote via ssh
PGARCHIVE_MODE="0" 

ARCHIVE_USER=pgsql
ARCHIVE_SERVER=192.168.4.223
ARCHIVE_SERVER_SSH_PORT=22

# 0: disables standby
# 1: enables standby
PGSTANDBY_ENABLED="0" 

STANDBY_USER=pgsql
STANDBY_SERVER=192.168.4.223
STANDBY_SERVER_SSH_PORT=22

# If you want to recover, set RECOVERY_MODE
# 0: local
# 1: standby
RECOVERY_MODE=0
